### ISSUE TITLE
Bitcoin QR code generation issue

### ISSUE THREAD

**Issue by Wikinaut** [jens-duttke/jsqr#1]
When you generate with http://www.jsqr.de (text mode) `bitcoin:1JSQRqsGniGHejkntZv5JkoFdMj8MPuyHu` this is not correctly encoded, a common bitcoin wallet fails to decode the QR code.

However, when generating with ZXing online generator, it works.
https://zxing.appspot.com/generator/

https://zxing.org/w/chart?cht=qr&chs=350x350&chld=L&choe=UTF-8&chl=bitcoin%3A1JSQRqsGniGHejkntZv5JkoFdMj8MPuyHu

**Comment by jens-duttke** [comment]
Thanks for reporting this issue.

The encoder on http://www.jsqr.de/encode.html encodes the data always using the encoding mode UTF8_SIGNATURE, which adds a Byte Order Mark to the beginning of the string, to tell the decoder, how to interprete the data, even if there are no UTF-8 encoded characters in the string.

Seems like neither the decoder you've used, nor the ZXing online generator support Byte Order Marks, so they both work together.

Anyhow, since in your specific case, your string does not include any UTF-8 characters, it's not required to add a BOM to the string.

So, I've implemented a detection, which checks the used characters, and use the BYTE encoding method instead of UTF8_SIGNATURE, if the string does not contain UTF-8 characters.

Beside that, I've implemented a new encoding option for Bitcoins:
http://www.jsqr.de/encode-bitcoin.html

Can you please check that with your bitcoin wallet software again?

**Comment by Wikinaut** [comment]
Yep, confirmed, it works.
I now used this test (with Umlauts!) 

```
bitcoin:1JSQRqsGniGHejkntZv5JkoFdMj8MPuyHu?label=test1%20Test2äöüß&amount=0.10
```

and it works with your new page.

BTW, I use this https://play.google.com/store/apps/details?id=de.schildbach.wallet&hl=de bitcoin wallet, source code is also on Github.
